### ISSUE TITLE
为什么要assert all_boxes和all_scores的数量不相等？

### ISSUE THREAD

**Issue by hxqiu** [ping28198/Thailand_projects#1]
https://github.com/ping28198/Thailand_projects/blob/c27eed5cc74420e6d0e8b398f1a3bcd50b5fe23c/Projects/Test_tensorflow_cpp/Test_tensorflow_cpp/yolo_v3.cpp#L361

你好，请教一下，为什么这一行要assert二者不相等，all_boxes和all_scores的数量不是应该相等吗？

**Comment by ping28198** [comment]
没有意义，可以删除。
